### ISSUE TITLE
Add Verbose Test Output

### ISSUE THREAD

**Issue by AndyM84** [unittest-cpp/unittest-cpp#103]
It'd be pretty helpful to get more verbose test pass/fail output along with individual test timings.  I'd be happy to do this myself, but it would involve refactoring the way tests are run and I'm not sure I should be so pretentious to think I know the best approach.

My thought on this had been to adjust `ExecuteTest<T>` to call a new `TestResults::OnTestSuccess()` method so that you have the option to see pass/fail notices via an added `m_showTestPassFail` flag for the `TestRunnerStdout` runner.

Open to other suggestions, someone else doing it, or getting a go-ahead to do it myself if that really is a reasonable approach.

**Comment by grahamreeds** [comment]
Why do you need to know the test timings? You write the tests and move on.
Once you have enough tests, maybe some of them could be refactored to be
faster but there is already a machanism to fail tests that take longer than
a specified time.

As for passing/failing, again the reason is why? Failing tests are more
important than passing ones.

GR

**Comment by AndyM84** [comment]
The short answer to both of those questions is "Continuous Integration."

The long answer is that I am implementing a project that will utilize UnitTest++ inside of TeamCity and can build better test/coverage reports if I have individual pass/fail notifications.  Furthermore, though it's not at all a performance test, using individual timings as a metric to detect performance regression is a great start that will keep development pointed in the right direction.

**Comment by pjohnmeyer** [comment]
It sounds to me that you may wish to either run your tests with the existing XmlTestReporter, a custom TestReporter implementation, or a CompositeTestReporter that uses them both. TestReporters already receive a test start and test complete event. This of course means you can't use `UnitTest::RunAllTests`, but rather have to instantiate your reporter, instantiate a TestRunner, then call RunTestsIf on that runner. See the implementation of RunAllTests in TestRunner.cpp for an example.

Does that help?

**Comment by grahamreeds** [comment]
I used UnitTest++ several years ago with a tool called Bullseye which gave
the coverage metric which helped write tests to cover the bits we missed
while writing the application (the licence turned up late in development).

While the coverage metric was nice we always ran at 100% passing, and if
any tests failed the code would be fixed before moving on.

Again there is already a feature to fail tests that takes longer than a
configurable time limit.

Also it means someone has to read these reports. If you have failing tests
then telling you that they failed in .1 second or 10 seconds. They are
still failing.

You could add a new report tool - use one of the existing ones as a base
but I for one see little value in timing failing tests.

GR

Sent from my Nexus 5.

The short answer to both of those questions is "Continuous Integration."

The long answer is that I am implementing a project that will utilize
UnitTest++ inside of TeamCity and can build better test/coverage reports if
I have individual pass/fail notifications. Furthermore, though it's not at
all a performance test, using individual timings as a metric to detect
performance regression is a great start that will keep development pointed
in the right direction.

—
Reply to this email directly or view it on GitHub
<https://github.com/unittest-cpp/unittest-cpp/issues/103#issuecomment-191414735>
.

**Comment by AndyM84** [comment]
@pjohnmeyer: I looked into doing that first based on the way the system is setup, but the approach doesn't actually get me the functionality that I need.  `ExecuteTest<T>` doesn't actually provide pass/fail information to the `OnTestFinished` method, so either way I'd have to refactor something (it may be a better approach to provide that information to `OnTestFinished` instead of adding a new 'success' method).

@grahamreeds: As I mentioned before, the value in timing individual tests is for performance regression.  It's great that you can provide a baseline threshold of X seconds/etc to say that any test running longer than that should fail, but I'd rather see a relative indicator of test run times between different builds.  That's much more useful than saying "well at least all the tests finished within 3 seconds still" in my mind.

**Comment by pjohnmeyer** [comment]
@AndyM84 I believe if you use the XmlTestReporter, TeamCity can process the XML file and present it -- it contains all successes, failures, and timings, which I believe is what you want.

If you wish to have another format of report with this information in it, you should be able to do what you want by implementing a custom `TestReporter` that maintains some state. Specifically, clear a flag to indicate there are no failures yet in your override of `ReportTestStart`. Then, set that flag in `ReportFailure`. In `ReportTestFinish`, then, you can output success information if the flag is clear, failure information if it is set.

Even though adding the failure information to `ReportTestFinish` isn't a bad idea, it would break any and all custom TestReporters in existence in the wild unless it were embedded in `TestDetails` -- but this would also violate the responsibility of TestDetails. Adding a virtual `ReportFailedTestFinish` that by default just calls `ReportTestFinish` might be a way around this, but ultimately I'm just not sure it's necessary.

If you need additional help achieving exactly what you want, I'd be happy to get on a chat or screen-share sometime -- or if you can even just write in the issue what you'd like to see the output look like, that would be very helpful in understanding the problem.

**Comment by AndyM84** [comment]
@pjohnmeyer Thanks for that, I'll give the XmlTestReporter a try.  If it does what you say, then I'd be perfectly satisfied using XML as the format.  Much appreciated!

**Comment by pjohnmeyer** [comment]
@AndyM84 Have you gotten the results you were hoping for?

If you ended up needing to write a custom TestReporter, I'd be keen to see what you ultimately did.

**Comment by AndyM84** [comment]
Sorry for the delay @pjohnmeyer.  The `XmlTestReporter` got me all the information that I needed, so I didn't *have* to create a new reporter.  I may still end up creating one, but probably just because I will end up having a custom format I want to massage that data into for our coverage system.  Thanks again!

    <?xml version="1.0"?>
    <unittest-results tests="22" failedtests="0" failures="0" time="0.00570935">
        <test suite="DispatchBase" name="ValidBasicDispatch" time="0.000153949"/>
        <test suite="DispatchBase" name="InvalidBasicDispatch" time="6.37176e-05"/>
        <test suite="NodeBase" name="ValidBasicNode" time="6.15794e-05"/>
        <test suite="NodeBase" name="InvalidBasicNode" time="7.69743e-05"/>
        <test suite="CliDispatchTest" name="CliDispatchProducesCorrectCount" time="0.000377174"/>
        <test suite="CliDispatchTest" name="CliDispatchProducesCorrectRawString" time="0.000254443"/>
        <test suite="CliDispatchTest" name="CliDispatchProducesCorrectRawParameters" time="0.000360924"/>
        <test suite="CliDispatchTest" name="CliDispatchProducesCorrectVariantMapCount" time="0.000526846"/>
        <test suite="CliDispatchTest" name="CliDispatchProduceCorreVariantMapValues" time="0.000686781"/>
        <test suite="CliDispatchTest" name="CliDispatchProducesCorrectInvariantMapCount" time="0.000687209"/>
        <test suite="CliDispatchTest" name="CliDispatchProducesCorrectInvariantMapValues" time="0.000606386"/>
        <test suite="ChainHelperTest" name="NonConsumableStatefulChainGetsCorrectCount" time="0.00016635"/>
        <test suite="ChainHelperTest" name="ConsumableStatefulChainGetsCorrectCount" time="0.000153949"/>
        <test suite="ChainHelperTest" name="NonConsumableNonStatefulChainGetsCorrectCount" time="0.000299344"/>
        <test suite="ChainHelperTest" name="ConsumableNonStatefulChainGetsCorrectCount" time="8.80928e-05"/>
        <test suite="ChainHelperTest" name="NonConsumableStatefulChainGetsCorrectValue" time="0.000140692"/>
        <test suite="ChainHelperTest" name="ConsumableStatefulChainGetsCorrectValue" time="0.000124442"/>
        <test suite="ChainHelperTest" name="NonConsumableNonStatefulChainGetsCorrectValue" time="0.000108192"/>
        <test suite="ChainHelperTest" name="ConsumableNonStatefulChainGetsCorrectValue" time="0.00010306"/>
        <test suite="ChainHelperTest" name="EventChainReturnsCorrectCount" time="0.000445168"/>
        <test suite="ChainHelperTest" name="EventChainReturnsCorrectValue" time="8.59546e-05"/>
        <test suite="DefaultSuite" name="Sanity" time="2.52305e-05"/>
    </unittest-results>
