### ISSUE TITLE
'make install' is doubling UnitTest++ directory in include dir

### ISSUE THREAD

**Issue by tiberiomoliveira** [unittest-cpp/unittest-cpp#105]
When I perform the command `make install`, the include directory has UnitTest++ created twice:
`/usr/local/include/UnitTest++/UnitTest++/`

I was using the default configuration, but the same happens when I use a different directory on `--includedir` configure's parameter. In order to solve the problem I edited the file Makefile.in removing the UnitTest++ from the line 496:
`pkgincludedir = $(includedir)/UnitTest++/`
So now the line is:
`pkgincludedir = $(includedir)/`

Now the command `make install` creates the right include path. I did this change because the variable `nobase_pkgincludeHEADERS` already has the UnitTest++ included in its files path. Maybe that is the cause of the repeated directory in the include path.

Has anyone experienced the same problem?

Thanks.

**Comment by fcami** [comment]
Confirmed on Fedora.
I'll apply the same fix before updating the package.

**Comment by pjohnmeyer** [comment]
Fixed by #109
