### ISSUE TITLE
I see no verbose flag

### ISSUE THREAD

**Issue by RussNelson** [unittest-cpp/unittest-cpp#108]
I see no verbose flag. I am looking at a library that has tests using unittest-cpp. It's reporting a message not in the library, but very likely from some other library. No idea which test is provoking that error message. It would be nice if I could run the test executable with a flag that says what test is currently running. Am I missing something in the documentation or does such a feature really not exist?

**Comment by pjohnmeyer** [comment]
The default `TestReporter` for UnitTest++ does not report progress, nor does it have a flag to do so -- assuming that default is the one in use. UnitTest++ does not create the `main` function for the test executable, so any special reporting, command-line flags, etc. are not in its purview.

It may be that the particular project has something set up for verbose reporting, but you would need to examine that project's source for such a feature.
