### ISSUE TITLE
The wiki has paths that are invalid on windows

### ISSUE THREAD

**Issue by jumonatr** [unittest-cpp/unittest-cpp#134]
The ":" character found in some wiki pages creates invalid paths when cloning unittest-cpp on windows. This is troublesome for some CI systems. I'm not sure what the process is for modifying the wiki so I thought I would start by creating an issue.

Writing More Tests With the Bowling Game Kata: Test Two
Writing More Tests With the Bowling Game Kata: Tests Three through Five
Writing More Tests With the Bowling Game Kata: Adding Exceptions

**Comment by pjohnmeyer** [comment]
Fixed by #135; thanks!
