### ISSUE TITLE
The ChangeLog is empty and there is no NEWS file

### ISSUE THREAD

**Issue by ryandesign** [unittest-cpp/unittest-cpp#138]
The ChangeLog is empty and there is no NEWS file. This is not helpful to those trying to figure out what changed.

A list of issues and pull requests, or a log of commit messages, is not a substitute for a curated NEWS file.

**Comment by pjohnmeyer** [comment]
You are right that the ChangeLog is empty; that file should be deleted and was never intended to be populated.

You can find the change log in the README here: https://github.com/unittest-cpp/unittest-cpp/blob/master/README.md#historic-release-notes

I don't really intend to add a separate NEWS file, but I will delete the ChangeLog.
