### ISSUE TITLE
float equality problem

### ISSUE THREAD

**Issue by hackereg35** [unittest-cpp/unittest-cpp#142]
Hi, I'm building a math lib for my kernel but the problem is that the tests fail even if it's equal i get thing message and smiler all the time
`error: Failure in ln_t: Expected 1.38629 but was 1.38629`
? even if i typed the full value returned from the function that i get throw `cout` which is
 `1.3862943611198906188573809483699506017728708684444427490234375` `cout` precision is 200
i still get the same result

**Comment by grahamreeds** [comment]
Without seeing the code you are actually testing I can only speculate but
there probably is some variation in the bits. You should never compare
floating point numbers. 10.0 + 1.0 != 11.0 (probably - untested). You
 should use CHECK_CLOSE

https://github.com/unittest-cpp/unittest-cpp/wiki/Macro-and-Parameter-Reference

**Comment by pjohnmeyer** [comment]
@grahamreeds is correct ; this is especially likely when some small errors are compounded by math operations. The examples I always use are 0.0125 and 0.025; these are very simple decimal numbers, but they cannot be represented precisely in the IEEE-754 binary floating point representation. As a result, `0.0125 + 0.0125 != 0.025`.

Closing the issue but will reopen if you can provide example code that exhibits a problem with the method.
