### ISSUE TITLE
Comparation between signed and unsigned with constant 

### ISSUE THREAD

**Issue by ntfshard** [unittest-cpp/unittest-cpp#152]
Hello

I've got $subj issue with next simple TEST:
`std::vector<int> t(4); CHECK_EQUAL(4, t.size());`

compiler: g++ 5.3.1 (Opensuse x64, package name: g++-5) with -Wall -std=c++14 keys
unittest-cpp got from git
[error.txt](https://github.com/unittest-cpp/unittest-cpp/files/888028/error.txt)

**Comment by CaseyCarter** [comment]
`4` is a (signed) integer literal, and `t.size()` has an unspecified unsigned integral type. If you compare them with compiler warnings for signed/unsigned comparison enabled, you will get this warning.

Try `CHECK_EQUAL(4u, t.size())` instead.

**Comment by ntfshard** [comment]
Thank you for response
This approach should help but my concern about usability.
Lines `if(4 == t.size())` and `assert(4 ==t.size)` is a legit for any compiler;
But in the another hand it could be a really hard to "beat" template argument deduction.
Could you please add some notes about it in a wiki and close the ticket.

M.
