### ISSUE TITLE
Compatible mocking framework

### ISSUE THREAD

**Issue by albert-tomanek** [unittest-cpp/unittest-cpp#162]
What mocking/stubbing framework would you recommend I use with UnitTest++?

**Comment by grahamreeds** [comment]
I use HippoMocks[1] though I have been looking at switching to FakeIt[2]
but not done anything strenuous with it yet.

GR

[1] http://hippomocks.com/Main_Page
[2] https://github.com/eranpeer/FakeIt

**Comment by albert-tomanek** [comment]
Thanks! I'll have a look at those.
