### ISSUE TITLE
CrashingTestsAreReportedAsFailures crashes on OS X 10.8.3 and Xcode 4.6.2

### ISSUE THREAD

**Issue by bjoernknafla** [unittest-cpp/unittest-cpp#45]
When running the unittests of unittest-cpp on Mac OS X 10.8.3 in Xcode 4.6.2 they crash.

The following errors are reported:
When not attaching a debugger on crash:
libc++abi.dylib: terminate called without an active exception

When attaching lldb on crash:
error: address doesn't contain a section that points to a section in a object file
Second entry of the backtrace: ExecuteTest.h, line 35 

When attaching gdb on crash:
Program received signal: "EXC_BAD_ACCESS" 
in TestTest.cpp line 85

I tried to add more signal handlers (for SIGABRT and SIGTERM) but they were not called (the breakpoint I set into the handler function didn't trigger - which might be just how the debugger interacts with certain signals).

I'm unsure if the crash provoking code in TestTest.cpp line 85 can be caught via signals as I don't have much experience with them. Therefore I am unsure if this is a bug or expected behavior but wanted to report it should there be a fix for this.

**Comment by pjohnmeyer** [comment]
I have looked into this deeper, and unfortunately the setting mentioned previously is stored in user workspace settings, something CMake does not create or modify. This issue cannot be resolved within the scope of the project.
