### ISSUE TITLE
Allow "asynchronous" unit test -> new Test Macro ?

### ISSUE THREAD

**Issue by asmodehn** [unittest-cpp/unittest-cpp#62]
In my case I need to run tests that trigger a behavior, and then wait for a callback/signal/flag to keep going...
I am using a main loop from another library. I want to trigger some behavior, wait for a few loops, and then check if the result is as expected.
This might even be useful for "true" concurrency with threads, although it s not my goal here...

At the moment I cannot do this with the current Test macros, because they expect a test to be completely included in one function ( void RunImpl() ).

Something that would allow me to implement that behavior would be a Macro like : 

```C
#define TEST_FIXTURE_PART(Fixture, Name, Part) TEST_FIXTURE_PART_EX(Fixture, Name, Part, UnitTest::Test::GetTestList())
```

where TEST_FEATURE_PART_EX defines multiple runImpl like : 

```C
std::pair<std::function<bool()>,UnitTest::TimeConstraint> Fixture##Name##Helper::RunImpl##Part()
```

Ideally I want use this macro like this : 

```C
#define ACCEPTABLE_DELAY(60)

TEST_FIXTURE_PART(OfflineSave, ClearSymmetric_Sync, 1)
{
  std::string original_value = "This is my save that I don't want to loose";
  m_save.requestSaveData(original_value);
       
  return std::make_pair([=]() -> bool{
    m_save.isSaved() && m_saved
  },
  UNITTEST_TIME_CONSTRAINT(ACCEPTABLE_DELAY)
  );
}

TEST_FIXTURE_PART(OfflineSave, ClearSymmetric_Sync, 2)
{
  m_save.requestLoadData();
        
  return std::make_pair([=]() -> bool{
    m_save.isLoaded() && m_loaded
  },
  UNITTEST_TIME_CONSTRAINT(ACCEPTABLE_DELAY)
  );
}

TEST_FIXTURE_PART(OfflineSave, ClearSymmetric_Sync, 3)
{
  std::string loaded_value = m_save.getData();    
  CHECK(original_value == loaded_value);
}
```

Please note in here that the Fixture is the same instance in every test part.
Also now you can see each test part returns both a lambda function to run ( to evaluate when it s suitable to run the next test part ), and a time limit for this condition to be met ( or the test will fail ).

In between each part, the rest of the code can run ( main update loop, and so on... ), via a new Runner that can identify there are multiple parts to this test ( using the return value of runImpl() )

I tried to implement such a feature, but honestly I am not familiar with unittest-cpp code yet and the macros makes it difficult to debug my new code...
So I was wondering : 
- Is this feature doable / suitable for unittest-cpp or not ?
- If not, am I looking at it the wrong way and there is another/better way to do that ?

**Comment by asmodehn** [comment]
My case has to do with rule 2 indeed.

At first i thought i didnt need to test the library functionality, but it
turns out I do.
Half to find out how it s working, Half to make sure it s always working
the same way.
Many c++ libraries out there are simply not tested / documented enough.

The library is a sdk connecting to a REST server with some modification to
make it build ( yes, it s not even building out of the shelf ) Writing a
mock for it would be possible but i ll probably have to redo it every time
there is an update done on it.

As you said I do not want to test the SDK. However is it useful to check
that the behavior of what i use in the sdk doesn't change every time i
update it. A server logic change for example will not show up unless i test
the whole chain. So in that case a mock would not fit the purpose.

So it s indeed a defensive practice that i realized, even if it is more
suited to integration testing, could be useful to have in a unit testing
framework.

**Comment by pjohnmeyer** [comment]
@asmodehn If you're still interested in discussing this further I'd be happy to see a proposed implementation with a sample of how it would be used, but right now I'm still erring on the side of this being outside the scope of UnitTest++.

Perhaps it could be designed to be purely additive -- in other words, requires no changes to the existing code, but rather is another "user" of the library?

**Comment by asmodehn** [comment]
The way I see it, it is an additional macro, to enable more advanced use of unittest-cpp, in the way that I dont have to have my test in one function. I can start in one function and check if it succeeded in another...

I think I would have to spend some time investigating how it all work together and figure out a proper implementation for it. However the project I was planning to use this for recently came to an end, and I started to spend time on too many other things, so I am not sure when I will get the time to do this.

**Comment by pjohnmeyer** [comment]
Okay. I am going to close this issue; if you ever get around to revisiting this you can open a new one or ask me to re-open this one.

Thanks!
