### ISSUE TITLE
CHECK macros redefinition

### ISSUE THREAD

**Issue by sinjar666** [unittest-cpp/unittest-cpp#64]
CheckMacros.h has a ifdef to check if 
CHECK, CHECK_EQUAL, etc have been already defined.
This gives me problems when some code which links to other libraries (like glog) which have a CHECK macro (but with different definition) are being tested.
Namespaces cant help with preprocessor macros.
How can I work around this?

If the check macros made calls to static methods within a class thats in the UnitTest namespace, maybe this can be solved by calling the static methods instead of macros in such cases.

**Comment by sinjar666** [comment]
Still waiting for some response on this

**Comment by grahamreeds** [comment]
I think you might have to fork the project and change it so it is UT_CHECK, UT_CHECK_EQUAL.

I quite dislike macro programming but in this instance it does hide a lot of the mechanics away.  If we could get a system which can do away with the macros but still hid the complexity then I would be all for it.

**Comment by sinjar666** [comment]
True, macros does hide the mechanics.
However macros with the name CHECK are quite commonly redefined in other libraries as well (Google Glog for example). Facebook's folly have their own CHECK_THROW().

I guess I would fork this and go for the UT_ prefixes to the macro names
Thanks for the reply @grahamreeds

**Comment by pjohnmeyer** [comment]
@sinjar666 please take a look at #114 and tell me if this would address this issue.

**Comment by pjohnmeyer** [comment]
#114 gives users a way to disable the "short" macros and use longer, "namespaced" macros that are prefixed `UNITTEST_`. This is in no way perfect but does address this particular issue.

**Comment by sinjar666** [comment]
Sorry for being almost a year too late but had ended up doing something similar. UT_ instead of UNITTEST_  :)
