### ISSUE TITLE
please sync unittest-cpp with casablanca fork

### ISSUE THREAD

**Issue by LocutusOfBorg** [unittest-cpp/unittest-cpp#72]
Hi, since the Debian package is from a dead upstream, and you seems to be the new one, I would like to update the package with your fork.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784665

unfortunately a package I use (casablanca) did a fork with some new classes that makes the package fail to build with your code.
http://casablanca.codeplex.com/SourceControl/latest#Release/tests/common/UnitTestpp/
how do you feel about merging them to your fork?

after that I'll ask Debian to switch to your code :)

**Comment by grahamreeds** [comment]
I haven't taken a look at Casablanca yet, but really shouldn't they be upgrading to us? :)

**Comment by LocutusOfBorg** [comment]
you seem to lack of (e.g. GlobalSettings.cpp).

I don't know if you do it in a different way or it is something new from them...

**Comment by grahamreeds** [comment]
Had a quick look over lunch and got Casablanca to build and run the tests with VS2012.  

At the risk of going OT; taking a peek at their UnitTestpp cmake file it is quite a bit simpler than the behemoth we use.  Would it be worth moving to something simpler like theirs? Not being a 'brain' at CMake every time I look in ours I get palpitations.

**Comment by grahamreeds** [comment]
Another thought I had yesterday afternoon (but forgot to post) is to put UnitTest++ on NuGet, so then they can remove the hard coding of that version and pull in the version like they do with Boost.

Note: I have not looked at what you need to do to get a package on NuGet.

**Comment by LocutusOfBorg** [comment]
I don't know and understand what NuGet is, do you think you can help me on this matter?

**Comment by grahamreeds** [comment]
NuGet is Microsoft's way of managing dependencies and getting source
packages.

If you build Casablanca in Visual Studio it will automatically pull in
Boost, zlib, ssl and several others automatically.

Putting UnitTest++ into NuGet will allow us to update Casablanca so it
treats it like any other dependency instead of a special case. Additionally
it improves the visibility of UnitTest++ and removes an older version from
the wild.

That is if Casablanca team accept the changes.

GR

Sent from my Nexus 5.

I don't know and understand what NuGet is, do you think you can help me on
this matter?

—
Reply to this email directly or view it on GitHub
<https://github.com/unittest-cpp/unittest-cpp/issues/72#issuecomment-103936051>
.

**Comment by LocutusOfBorg** [comment]
that would be awesome!

**Comment by paxos1977** [comment]
> At the risk of going OT; taking a peek at their UnitTestpp cmake file it is quite a bit simpler than the behemoth we use. Would it be worth moving to something simpler like theirs? Not being a 'brain' at CMake every time I look in ours I get palpitations.

Ah @grahamreeds you're so cute. If you had *any* experience writing CMake files, you'd probably realize how very simple this one is - by no means a behemoth. Also, I looked at (UnitTestpp fork)[https://github.com/paulecoyote/unittestpp] and there is no CMakeLists.txt file there. I'm I looking at the wrong project? 

IMO, if anything, unittest-cpp's CMake implementation is lacking a little bit of necessary structure.

**Comment by grahamreeds** [comment]
My comment was about Casablanca unittest++ cmake file.

https://casablanca.codeplex.com/SourceControl/latest#Release/tests/common/UnitTestpp/CMakeLists.txt

GR

Sent from my Nexus 5.

At the risk of going OT; taking a peek at their UnitTestpp cmake file it is
quite a bit simpler than the behemoth we use. Would it be worth moving to
something simpler like theirs? Not being a 'brain' at CMake every time I
look in ours I get palpitations.

Ah @grahamreeds <https://github.com/grahamreeds> you're so cute. If you had
*any* experience writing CMake files, you'd probably realize how very
simple this one is - by no means a behemoth. Also, I looked at (UnitTestpp
fork)[https://github.com/paulecoyote/unittestpp] and there is no
CMakeLists.txt file there. I'm I looking at the wrong project?

IMO, if anything, unittest-cpp's CMake implementation is lacking a little
bit of necessary structure.

—
Reply to this email directly or view it on GitHub
<https://github.com/unittest-cpp/unittest-cpp/issues/72#issuecomment-138017962>
.

**Comment by pjohnmeyer** [comment]
GlobalSettings is not suitable for incorporation into the current mainline (I think it is a holdover from the older version they began with). It includes intrusive changes to UnitTest::TestRunner that could be handled externally to the UnitTest++ library.

Take-aways from this thread:

1. We should build a NuGet package (was already on my radar, but confirmed), and make updating it part of the release process.
2. Somebody should investigate what it would take to then incorporate current UnitTest++ into Casablanca, and offer up a patch.

I'm going to open these as two new tickets and close this one once they are written.

**Comment by LocutusOfBorg** [comment]
thanks a lot!!!

**Comment by pjohnmeyer** [comment]
@LocutusOfBorg you're welcome. I wrote #81 and #82 to capture what we actually want to do, and marked this one as duplicate. I'll note that the version on codeplex is not the current casablanca project page; https://github.com/Microsoft/cpprestsdk is.

Anybody want to take a stab at those feel free.

**Comment by grahamreeds** [comment]
Just looked and its used in one unit (TestRunner) and relates to timeouts.

Beyond that I can't say until I get some spare time.

GR
