### ISSUE TITLE
How to safely terminate the execution of a multi-threaded case?

### ISSUE THREAD

**Issue by zxjcarrot** [unittest-cpp/unittest-cpp#74]
Some of my test cases might spawn threads and might block indefinitely, or for very long time.
So I need a way to terminate those cases and mark them as timed out.
Does unittest-cpp support this?

**Comment by paxos1977** [comment]
As a general rule of thumb, I recommend against multi-threaded unit tests. However, I understand it is necessary sometimes. 

There is functionality for failing tests that take too long. I believe it looks like this: 

    TEST(failLongRunningTests)
    {
        UNITTEST_TIME_CONSTRAINT(1000); // time allowed before a failure in ms
        // your code here
    }

**Comment by zxjcarrot** [comment]
I agree. After some digging on the internet, I found no way to do this safely. Guess I have to try some workarounds, such as spawning a child process with a time limit to run the test.
I've tried `UNITTEST_TIME_CONSTRAINT`, sadly it won't stop the thread after the timeout.
