### ISSUE TITLE
TestUnitTest++.exe Abort() called

### ISSUE THREAD

**Issue by paxos1977** [unittest-cpp/unittest-cpp#76]
Compiling UnitTest++ with Visual Studio 2015 Community Edition. Warning [C4297](https://msdn.microsoft.com/en-us/library/84e2zwhh.aspx) is triggered by TestTestMacros.cpp line 141. 

The key phrase in the MSDN documentation is that VS2015 is adding an implicit *noexcept* on all user destructors and deallocators. Throwing from a noexcept method causes abort() to be called on the process.

We can add the /Zc:implicitNoexcept when compiling to suppress the implicit noexcept behavior, but going forward I wonder if this is a valid test for C++11 code.

**Comment by paxos1977** [comment]
Specifically, we'd need to use `/Zc:implicitNoexcept-` to disable the addition of noexcept to user defined destructors.

**Comment by cmdrf** [comment]
There is a fork by Microsoft addressing this issue: https://github.com/Microsoft/unittest-cpp

**Comment by grahamreeds** [comment]
Which they are quite welcome to! :-)
