### ISSUE TITLE
Tests broken in Visual Studio 2010

### ISSUE THREAD

**Issue by grahamreeds** [unittest-cpp/unittest-cpp#84]
UnitTest++ fails to compile the tests in Visual Studio 2010, failing in TestTestMacros.cpp at Line 170.

This line has comment preceding it and a preprocessor version check.  Basically it says Visual Studio 2015 implicitly adds ```noexcept``` to destructors and any exceptions thrown will cause abort to be thrown.  The code is surrounded by a ```#if(_MSC_VER < 1900)```. I am guessing that ```_NOEXCEPT_OP``` macro is supposed to emulate ```noexcept``` where support is not available.  

However ```NOEXCEPT_OP``` is not ```#define```d for MSVC because the definitions (lines 19,21,29 and 31) are surrounded by ```#ifndef _MSC_VER``` and so they are never seen.

I am investigating a fix.

```
3>  TestTestMacros.cpp
3>..\tests\TestTestMacros.cpp(170): error C3646: '_NOEXCEPT_OP' : unknown override specifier
3>..\tests\TestTestMacros.cpp(170): error C2059: syntax error : 'constant'
3>..\tests\TestTestMacros.cpp(170): error C2091: function returns function
```

**Comment by grahamreeds** [comment]
Also Line 170 isn't visible to the Clang/GCC compilers due to the compiler check at line 167.  This is definitely wrong.

**Comment by grahamreeds** [comment]
Also this code is not visible to the clang/gcc compilers due to the compiler check at line 167.  This is definitely wrong.

**Comment by grahamreeds** [comment]
Created a patch and a pull request for it.  Hope I am doing this right.  How do you link and issue with the pull request?

**Comment by martinmoene** [comment]
Like PR #85.

**Comment by grahamreeds** [comment]
That was me. I couldn't see how to link a PR to an issue.  First time I
have ever done it in GH.

**Comment by pjohnmeyer** [comment]
Incorporated PR #85 . Need to update the Appveyor config to matrix build on multiple MSVC compilers.
