### ISSUE TITLE
Intermittent test failure when using Xcode generator

### ISSUE THREAD

**Issue by jasonhorsburgh** [unittest-cpp/unittest-cpp#90]
I appear to be getting an intermittent test failure in TestTestRunner.cpp [TestFinishIsCalledWithCorrectTime](https://github.com/unittest-cpp/unittest-cpp/blob/master/tests/TestTestRunner.cpp#L108) when using the Xcode cmake generator.

The test constraints check if the lastFinishedTestTime are within 0.005 and 0.050 but after adding logging code after the check then I am getting values just over the top limit (~0.053895). If I use the Makefiles generator then there isn't a problem as the time value comes out ~0.025113.

If I keep trying to build it then I will eventually get it to succeed.

The test just uses `usleep(20)` to create a delay so I'm not entirely sure about what would need to be done to fix it, or if it's even a problem with the code itself and more with how Xcode performs builds?

system info:
OS X: 10.11.2
Xcode: 7.2
CMake: 3.3.2

**Comment by grahamreeds** [comment]
Using sleep for anything is a bad idea. It only guarantees how long it will
sleep for, not when it will wake.

http://accu.org/index.php/journals/2185

GR

Sent from my Nexus 5.

I appear to be getting an intermittent test failure in TestTestRunner.cpp
TestFinishIsCalledWithCorrectTime
<https://github.com/unittest-cpp/unittest-cpp/blob/master/tests/TestTestRunner.cpp#L108>
when using the Xcode cmake generator.

The test constraints check if the lastFinishedTestTime are within 0.005 and
0.050 but after adding logging code after the check then I am getting
values just over the top limit (~0.053895). If I use the Makefiles
generator then there isn't a problem as the time value comes out ~0.025113.

If I keep trying to build it then I will eventually get it to succeed.

The test just uses usleep(20) to create a delay so I'm not entirely sure
about what would need to be done to fix it, or if it's even a problem with
the code itself and more with how Xcode performs builds?

system info:
OS X: 10.11.2
Xcode: 7.2
CMake: 3.3.2

—
Reply to this email directly or view it on GitHub
<https://github.com/unittest-cpp/unittest-cpp/issues/90>.

**Comment by grahamreeds** [comment]
In addition to what I said previously, the correct way to test time
failures is to return the elapsed time as a value and fail on that, not to
use a non standard function that may or may not perform as expected.

So, for example you would have something like

```
TEST(foo)
{
    TestObject to;
    to.setMaxTestTime(200ms);
    TimeDelta td(201ms);
    to.AddTest("bar", td);
    CHECK_EQUAL(to.FailedTests, 1);
}
```
So you don't have to wait for an elapsed time, you get the failure
instantly.

GR
