### ISSUE TITLE
Provide a CMake Package Configuration File

### ISSUE THREAD

**Issue by stubb** [unittest-cpp/unittest-cpp#99]
It would be great if a CMake package configuration file would be installed/provided altogether with the lib itself. So everyone running an own CMake project could include/find unittest++ easily with the Cmake command find_package().
See https://cmake.org/Wiki/CMake/Tutorials/Packaging for details.

**Comment by pjohnmeyer** [comment]
Agreed. This is a duplicate of #89, though, so I'm closing it.

**Comment by pjohnmeyer** [comment]
Ah, disregard previous comment -- related but not the same.

**Comment by stubb** [comment]
Thanks!
